---
title: "ISLR Chapter4 "
author: "ACO"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: true
    toc_depth: '6'
  html_document:
    df_print: paged
    toc: true
    toc_depth: '6'
urlcolor: blue
subtitle: 'Classification'
---

\newpage
```{r, include=FALSE}
knitr::opts_chunk$set(echo = T, warning=FALSE,message=FALSE,attr.source='.numberLines',attr.output='.numberLines', fig.align='center', dpi=350, fig.width=15, fig.height=15)
```

# 4.7.1 The stock market data

```{r}
library(ISLR2)
```

```{r}
names(Smarket)
```

```{r}
pairs(Smarket)
```

```{r}
cor(Smarket[,-9])
```

\newpage
# 4.7.2 Logistic Regression

```{r}
glm.fits <- glm(
  Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
  data = Smarket , family = binomial
)
summary(glm.fits)
```

```{r}
glm_probs <- predict(glm.fits , type = "response")
glm_probs[1:10]
```

```{r}
contrasts(Smarket$Direction)
```

```{r}
glm_pred <- rep("Down", 1250)
glm_pred[glm_probs > .5] = "Up"
```

```{r}
table(glm_pred , Smarket$Direction)
```

```{r}
mean(glm_pred == Smarket$Direction)
```


```{r}
train <- Smarket$Year < 2005
Smarket_2005 <- Smarket[!train, ]
dim(Smarket_2005)
Direction_2005 <- Smarket_2005$Direction
```

```{r}
glm_fits <- glm(
  Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume, 
  data = Smarket , family = binomial , subset = train
)
glm_probs <- predict(
  glm_fits , Smarket_2005,
  type = "response")
```

```{r}
glm_pred <- rep("Down", 252)
glm_pred[glm_probs > .5] = "Up"
table(glm_pred , Direction_2005)
#
mean(glm_pred == as.character(Direction_2005))
mean(glm_pred != as.character(Direction_2005))
```

```{r}
glm_fits <- glm(
  Direction~Lag1 + Lag2 , data = Smarket ,
  family = binomial , subset = train)
glm_probs <- predict(
  glm_fits , Smarket_2005,
  type = "response")
glm_pred <- rep("Down", 252)
glm_pred[glm_probs > .5] = "Up"
table(glm_pred , Direction_2005)
mean(glm_pred == Direction_2005)
```


```{r}
predict(
  glm_fits, newdata = data.frame(Lag1 = c(1.2, 1.5), Lag2 = c(1.1, -0.8)),
  type = "response"
)
```

\newpage
# 4.7.3 Linear Discriminant Analysis

```{r}
library(MASS)
lda_fit <- lda(Direction~Lag1+Lag2, data = Smarket, subset = train)
lda_fit
```


```{r}
plot(lda_fit)
```


```{r}
lda_pred = predict(lda_fit, Smarket_2005)
names(lda_pred)
```

```{r}
lda_class = lda_pred$class
table(lda_class, Direction_2005)
mean(lda_class == Direction_2005)
```

# 4.7.4 Quadratic Discriminant Analysis

```{r}
qda_fit <- qda(Direction~Lag1+Lag2, data = Smarket, subset = train)
qda_fit
```

```{r}
qda_pred = predict(qda_fit, Smarket_2005)
qda_class = qda_pred$class
table(qda_class, Direction_2005)
mean(qda_class == Direction_2005)
```

# 4.7.5 Naive Bayes

```{r}
library(e1071)
```

```{r}
nb_fit <- naiveBayes(
  Direction ~ Lag1 + Lag2, data = Smarket, 
  subset = train)
nb_fit
```

```{r}
mean(Smarket$Lag1[train][Smarket$Direction[train] == "Down"])
sd(Smarket$Lag1[train][Smarket$Direction[train] == "Down"])
```

```{r}
nb_class <- predict(nb_fit , Smarket_2005)
table(nb_class , Direction_2005)
mean(nb_class == Direction_2005)
```

```{r}
nb_preds <- predict(nb_fit , Smarket_2005, type = "raw")
nb_preds[1:5, ]
```

# 4.7.6 K-Nearest Neighbour

```{r}
library(class)
train <- Smarket$Year < 2005
train_X <- Smarket[Smarket$Year < 2005 , 2:3]
test_X <- Smarket[Smarket$Year >= 2005 , 2:3]
train_Direction <- Smarket[Smarket$Year < 2005 , 9]
test_Direction <- Smarket[Smarket$Year >= 2005 , 9]
```

```{r}
set.seed(1)
knn_pred <- knn(train_X, test_X, train_Direction , k = 1)
table(knn_pred , test_Direction)
```

```{r}
set.seed(1)
knn_pred <- knn(train_X, test_X, train_Direction , k = 3)
table(knn_pred , test_Direction)
```

```{r}
dim(Caravan)
summary(Caravan$Purchase)
```

```{r}
standardized_X <- scale(Caravan[,-86])
var(Caravan[,1])
var(Caravan[,2])

var(standardized_X[,1])
var(standardized_X[,1])
```

```{r}
test <- 1:1000
train_X <- standardized_X[-test, ]
test_X <- standardized_X[test, ]
train_Y <- Caravan$Purchase[-test]
test_Y <- Caravan$Purchase[test]
set.seed(1)
knn_pred <- knn(train_X, test_X, train_Y  , k = 1)
mean(test_Y != knn_pred)
mean(test_Y != "No")
```


```{r}
table(knn_pred , test_Y)
```

```{r}
knn_pred <- knn(train_X, test_X, train_Y, k = 3)
table(knn_pred , test_Y)
#
knn_pred <- knn(train_X, test_X, train_Y, k = 5)
table(knn_pred , test_Y)
```

\newpage
# 4.7.7 Poisson Regression

```{r}
dim(Bikeshare)
names(Bikeshare)
```

```{r}
mod_lm <- lm(
  bikers~mnth + hr + workingday + temp + weathersit, 
  data = Bikeshare
)
summary(mod_lm)
```


```{r}
contrasts(Bikeshare$hr) = contr.sum(24)
contrasts(Bikeshare$mnth) = contr.sum(12)
mod_lm2 <- lm(
  bikers~mnth + hr + workingday + temp + weathersit , 
  data = Bikeshare
)
summary(mod_lm2)
```

```{r}
sum((predict(mod_lm) - predict(mod_lm2))^2)
```

```{r}
all.equal(predict(mod_lm), predict(mod_lm2))
```

```{r}
coef_months <- c(coef(mod_lm2)[2:12], -sum(coef(mod_lm2)[2:12]))
```


```{r}
plot(
  coef_months , xlab = "Month", ylab = "Coefficient",
  xaxt = "n", col = "blue", pch = 19, type = "o")
axis(side = 1, at = 1:12, 
     labels = c("J", "F", "M", "A",
                "M", "J", "J", "A", "S", "O", "N", "D"))

coef_hours <- c(coef(mod_lm2)[13:35],-sum(coef(mod_lm2)[13:35]))
plot(coef_hours , xlab = "Hour", ylab = "Coefficient",
     col = "blue", pch = 19, type = "o")
```

```{r}
mod_pois <- glm(
bikers~mnth + hr + workingday + temp + weathersit ,
data = Bikeshare , family = poisson
)
summary(mod_pois)
```


```{r}
coef_months <- c(coef(mod_pois)[2:12], -sum(coef(mod_pois)[2:12]))
```


```{r}
plot(
  coef_months , xlab = "Month", ylab = "Coefficient",
  xaxt = "n", col = "blue", pch = 19, type = "o")
axis(side = 1, at = 1:12, 
     labels = c("J", "F", "M", "A",
                "M", "J", "J", "A", "S", "O", "N", "D"))

coef_hours <- c(coef(mod_pois)[13:35],-sum(coef(mod_pois)[13:35]))
plot(coef_hours , xlab = "Hour", ylab = "Coefficient",
     col = "blue", pch = 19, type = "o")
```


```{r}
plot(predict(mod_lm2), predict(mod_pois , type = "response"))
abline(0, 1, col = 2, lwd = 3)
```





# Applied

## Q13

```{r}
head(Weekly)
```

### a

```{r}
boxplot(Today~Direction, data = Weekly, 
        col = c('blue', 'red'))
```

```{r}
pairs(Weekly[,1:7])
```

### b
```{r}
q13_model <- glm(Direction~., data = Weekly, family = binomial)
summary(q13_model)
```

```{r}
glm_probs <- predict(q13_model,type = 'response')
```

```{r}
glm_pred <- rep("Down", nrow(Weekly))
glm_pred[glm_probs > .5] = "Up"
```

```{r}
table(glm_pred , Weekly$Direction)
mean(glm_pred == Weekly$Direction)
```

### d

```{r}
train_X <- Weekly[Weekly$Year <= 2008 , -9]
test_X <- Weekly[Weekly$Year > 2008 , -9]
train_Direction <- Weekly[Weekly$Year <= 2008 , 9]
test_Direction <- Weekly[Weekly$Year > 2008 , 9]
```

```{r}
qda_fit <- qda(Direction~Lag2, data = Weekly, subset = train)
qda_pred = predict(qda_fit, test_X)
qda_class = qda_pred$class
table(qda_class, test_Direction)
mean(qda_class == test_Direction)

qda_fit <- qda(Direction~Lag2, data = Smarket, subset = train)
qda_pred = predict(qda_fit, test_X)
qda_class = qda_pred$class
table(qda_class, test_Direction)
mean(qda_class == test_Direction)
```







































